### ISSUE TITLE
这个脚本有个问题 

### ISSUE THREAD

**Issue by wxs315** [Sec-ant/MovieInfoGen#1]
豆瓣比如电视剧第二季 
他给出的IMDB地址是第一季
而相应的PT Gen 给出的就是第二季

测试
https://movie.douban.com/subject/33371988/
这个豆瓣地址 此脚本生成如下

[img]https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2582523074.jpg[/img]

◎译　　名　莎士比亚与哈撒韦：私人调查员 第二季
◎片　　名　Shakespeare & Hathaway: Private Investigators Season 2
◎年　　代　2019
◎产　　地　英国
◎语　　言　英语
◎上映日期　2019-02-25(英国)
◎IMDb评星  ★★★★★★★✦☆☆
◎IMDb评分  7.6/10 from 4,139 users
◎IMDb链接  https://www.imdb.com/title/tt7526498/
◎豆瓣链接　https://movie.douban.com/subject/33371988/
◎单集片长　45
◎集　　数　10
◎导　　演　皮奥特·斯科皮亚克 / Piotr Szkopiak
　　　　　　Richard Signy Richard Signy
　　　　　　卡罗莱娜·贾梅塔 / Carolina Giammetta
◎演　　员　马克·本顿 / Mark Benton
　　　　　　乔·乔伊纳 / Jo Joyner
　　　　　　杰玛·摩尔 / Jemma Moore

◎简　　介　

　　An oddball couple of private detectives named Luella Shakespeare and Frank Hathaway investigate crime in Stratford-upon-Avon.

PT Gen

[img]https://img9.doubanio.com/view/photo/l_ratio_poster/public/p2582523074.jpg[/img]

◎译　　名　莎士比亚与哈撒韦：私人调查员 第二季
◎片　　名　Shakespeare &amp; Hathaway: Private Investigators Season 2
◎年　　代　2019
◎产　　地　英国
◎语　　言　英语
◎上映日期　2019-02-25(英国)
◎IMDb链接　https://www.imdb.com/title/tt8253346/
◎豆瓣链接　https://movie.douban.com/subject/33371988/
◎集　　数　10
◎片　　长　45
◎导　　演　皮奥特·斯科皮亚克 Piotr Szkopiak (id:1034076)
　　　　　  Richard Signy Richard Signy (id:1297582)
　　　　　  卡罗莱娜·贾梅塔 Carolina Giammetta (id:1345102)
◎演　　员　马克·本顿 Mark Benton (id:1066026)
　　　　　  乔·乔伊纳 Jo Joyner (id:1189843)
　　　　　  杰玛·摩尔 Jemma Moore (id:1430847)

◎简　　介
　　An oddball couple of private detectives named Luella Shakespeare and Frank Hathaway investigate crime in Stratford-upon-Avon.

其中此脚本给的
https://www.imdb.com/title/tt7526498/
是第一季地址

正确第二季地址应该是
https://www.imdb.com/title/tt8253346/

**Comment by Sec-ant** [comment]
这是故意这么做的，IMDb 编号是对应某一剧集的而不是某一剧集某一季的，它不存在某一季的编号，你贴出的是第二季第一集的编号。

**Comment by Sec-ant** [comment]
没其他疑问的话，我先 close 了
